coverage:
  status:
    project:
      go:
        flags:
          - go
        target: auto
        threshold: 1%
      frontend:
        flags:
          - frontend
        target: auto
        threshold: 1%
    patch:
      go:
        flags:
          - go
        target: auto
      frontend:
        flags:
          - frontend
        target: auto
flags:
  go:
    paths:
      - internal/
      - cmd/
  frontend:
    paths:
      - web/src/
comment: false
