// Which README screenshot shows which page, and the README section built from
// that list (#549). The test beside this file fails when a page under
// src/routes has neither an entry here nor a place in EXCLUDED_ROUTES, so a
// new page can't be left out. capture-screenshots.mjs writes the files and
// update-readme-screenshots.ts rewrites the README section between its
// markers, so the release job's pull request carries both.

export interface Screenshot {
	file: string;
	// What the page is for; it is the image's alt text in the README.
	alt: string;
}

// The footer's own pages (the version link and Privacy & disclaimer).
export const EXCLUDED_ROUTES = ['/legal', '/releases'];

// Shown first and large, outside the "More screenshots" fold.
export const HERO_ROUTE = '/';

export const SCREENSHOTS: Record<string, Screenshot> = {
	'/': {
		file: 'screenshot-failure-overview.png',
		alt: 'Overview: pass rate, mean time to recovery, failed runs and where they fail, over a window you pick: 24 hours, 7 days or 30 days',
	},
	'/login': {
		file: 'screenshot-login.png',
		alt: 'Sign in: a passkey is the only way in, and the first visit registers it',
	},
	'/pipelines': {
		file: 'screenshot-overview.png',
		alt: "Pipelines list: each tracked pipeline's health status at a glance",
	},
	'/pipelines/[id]': {
		file: 'screenshot-pipeline-detail.png',
		alt: 'Pipeline detail: duration/failure-rate trend charts, step breakdown, and forge deep links',
	},
	'/pipelines/[id]/flaky-runs': {
		file: 'screenshot-flaky-runs.png',
		alt: 'Flaky runs: the runs where one flaky step failed, each linking to the run',
	},
	'/failures': {
		file: 'screenshot-root-cause.png',
		alt: 'Root cause diagnostics: failure categories and the failing steps behind them',
	},
	'/flaky': {
		file: 'screenshot-flaky.png',
		alt: "Flaky tests: each flaky step's last 40 results, failure rate and run count, with a quarantine action",
	},
	'/insights': {
		file: 'screenshot-insights.png',
		alt: 'Insights: how much of each GitHub token’s API rate limit is used, and which repositories share it',
	},
	'/repos': {
		file: 'screenshot-repos.png',
		alt: 'Repositories: the tracked repositories by forge, each with its masked token and ingestion status',
	},
	'/repos/[id]/usage': {
		file: 'screenshot-usage.png',
		alt: 'Usage view: runner-minutes per workflow',
	},
	'/runs': {
		file: 'screenshot-runs.png',
		alt: "Runs: each run's steps as a progress bar, with its commit, status and a link to the forge",
	},
	'/runs/[id]': {
		file: 'screenshot-run-detail.png',
		alt: "Run detail: one run's steps and their outcomes, with a log for a failed step",
	},
	'/settings': {
		file: 'screenshot-settings.png',
		alt: 'Settings: theme, the passkeys that can sign in, and the forge tokens saved for registering repositories',
	},
};

// Variants of a page above, not pages of their own.
export const EXTRA_SCREENSHOTS: Screenshot[] = [
	{
		file: 'screenshot-overview-dark.png',
		alt: 'Pipelines list in dark mode',
	},
	{
		file: 'screenshot-pipeline-detail-dark.png',
		alt: 'Pipeline detail in dark mode',
	},
];

export const START_MARKER = '<!-- screenshots:start -->';
export const END_MARKER = '<!-- screenshots:end -->';

const image = ({ file, alt }: Screenshot) => `![${alt}](docs/${file})`;

// The whole section between the markers, markers included.
export function renderScreenshotSection(): string {
	const rest = [
		...Object.entries(SCREENSHOTS)
			.filter(([route]) => route !== HERO_ROUTE)
			.map(([, screenshot]) => screenshot),
		...EXTRA_SCREENSHOTS,
	];

	return [
		START_MARKER,
		'<!-- Generated by web/scripts/update-readme-screenshots.ts. Do not edit by hand. -->',
		'',
		image(SCREENSHOTS[HERO_ROUTE]),
		'',
		'<details>',
		'<summary>More screenshots</summary>',
		'',
		rest.map(image).join('\n\n'),
		'',
		'</details>',
		END_MARKER,
	].join('\n');
}

// Swaps the section in a README for a fresh one.
export function replaceScreenshotSection(readme: string): string {
	const start = readme.indexOf(START_MARKER);
	const end = readme.indexOf(END_MARKER);
	if (start === -1 || end === -1 || end < start) {
		throw new Error(`README needs ${START_MARKER} and ${END_MARKER}`);
	}

	return (
		readme.slice(0, start) +
		renderScreenshotSection() +
		readme.slice(end + END_MARKER.length)
	);
}

// 'pipelines/[id]/+page.svelte' -> '/pipelines/[id]'.
export function routeOf(pageFile: string): string {
	const dir = pageFile.replace(/\/?\+page\.svelte$/, '');

	return `/${dir}`;
}
